image:
  repository: docker-remote.registry.kroger.com/pantsel/konga
  tag: 0.14.1

prepareImage:
  repository: docker-remote.registry.kroger.com/busybox

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "kong"
  hosts:
    - "konga.127-0-0-1.nip.io" 
env:
  node_tls_reject_unauthorized: "0"

postgresql:
  image: docker-remote.registry.kroger.com/postgres